### ISSUE TITLE
lib/TableMgr/AnyTable.py

### ISSUE THREAD

**Issue by joyeez** [joyeez/rc_backTest#3]
运行 ./bin/rc_backTest.py
编译报错：

  lib/TableMgr/AnyTable.py需要加入代码：
from pandas import (DataFrame, Series)
from rc_py_lib.rc_any_object import *

编译错误解决。

[songpj@localhost tests]$ python3 ../bin/rc_backTest.py
Traceback (most recent call last):
  File "../bin/rc_backTest.py", line 16, in <module>
    from StrategyRunner import *
  File "/home/songpj/PycharmProjects/rc_backTest/bin/../lib/StrategyRunner/__init__.py", line 3, in <module>
    from StrategyRunner.AnyStrategy import *
  File "/home/songpj/PycharmProjects/rc_backTest/bin/../lib/StrategyRunner/AnyStrategy.py", line 16, in <module>
    from TableMgr import *
  File "/home/songpj/PycharmProjects/rc_backTest/bin/../lib/TableMgr/__init__.py", line 1, in <module>
    from TableMgr.AnyTable import *
  File "/home/songpj/PycharmProjects/rc_backTest/bin/../lib/TableMgr/AnyTable.py", line 19, in <module>
    class AnyTable(rc_any_object):
TypeError: module.__init__() takes at most 2 arguments (3 given)

**Comment by joyeez** [comment]
Issue solved by updating AnyTable.py
