### ISSUE TITLE
TypeError: '<' not supported between instances of 'Period_t' and 'Period_t'

### ISSUE THREAD

**Issue by song-pj** [joyeez/rc_backTest#38]
In Context.py:

    def initialize(self):
        self.ts_df = self.SqlDbCenter.get_dataframe_of("trade_settings", conds={"testid": self.testid})
        #convert the string into Enum type
        self.ts_df['sec_grp'] = self.ts_df['sec_grp'].apply(lambda x: SecGrp_t(x))
        self.ts_df['period_level'] = self.ts_df['period_level'].apply(lambda x: Period_t(x))

the transformation will raise error if there are multiple period_level data in trade_settings.
The main cause is that when groupby the 'period_level' field,  the Enum object cannot be used with '>' operator.   

And it will also cause problem during the 'finest_period_level' calculation.

11-13-17 03:55 DEBUG: (rc_backTest.DataFeeder.Context_6.DataProxy) Loading in (SecGrp_t.CNSTK) data ... Please wait.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/pandas/core/algorithms.py", line 486, in safe_sort
    sorter = values.argsort()
TypeError: '<' not supported between instances of 'Period_t' and 'Period_t'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/pdb.py", line 1667, in main
    pdb._runscript(mainpyfile)
  File "/usr/local/lib/python3.6/pdb.py", line 1548, in _runscript
    self.run(statement)
  File "/usr/local/lib/python3.6/bdb.py", line 431, in run
    exec(cmd, globals, locals)
  File "<string>", line 1, in <module>
  File "/home/songpj/PycharmProjects/rc_backTest.spj/bin/rc_backTest.py", line 13, in <module>
    import _mypath
  File "/home/songpj/PycharmProjects/rc_backTest.spj/bin/rc_backTest.py", line 83, in main
    self.DataFeeder.main()
  File "../bin/../lib/DataFeeder/DataFeeder.py", line 38, in main
    self.per_test_id_proc(test_id)
  File "../bin/../lib/DataFeeder/DataFeeder.py", line 64, in per_test_id_proc
    context.setup()
  File "../bin/../lib/DataFeeder/Context.py", line 74, in setup
    self.DataProxy.setup_context_data()
  File "../bin/../lib/DataFeeder/DataProxy.py", line 66, in setup_context_data
    for period_level, sec_grp_period_data in period_based_sec_grp_data:
  File "/usr/local/lib/python3.6/site-packages/pandas/core/groupby.py", line 1755, in get_iterator
    splitter = self._get_splitter(data, axis=axis)
  File "/usr/local/lib/python3.6/site-packages/pandas/core/groupby.py", line 1761, in _get_splitter
    comp_ids, _, ngroups = self.group_info
  File "pandas/_libs/src/properties.pyx", line 34, in pandas._libs.lib.cache_readonly.__get__ (pandas/_libs/lib.c:44594)
  File "/usr/local/lib/python3.6/site-packages/pandas/core/groupby.py", line 1873, in group_info
    comp_ids, obs_group_ids = self._get_compressed_labels()
  File "/usr/local/lib/python3.6/site-packages/pandas/core/groupby.py", line 1880, in _get_compressed_labels
    all_labels = [ping.labels for ping in self.groupings]
  File "/usr/local/lib/python3.6/site-packages/pandas/core/groupby.py", line 1880, in <listcomp>
    all_labels = [ping.labels for ping in self.groupings]
  File "/usr/local/lib/python3.6/site-packages/pandas/core/groupby.py", line 2533, in labels
    self._make_labels()
  File "/usr/local/lib/python3.6/site-packages/pandas/core/groupby.py", line 2545, in _make_labels
    self.grouper, sort=self.sort)
  File "/usr/local/lib/python3.6/site-packages/pandas/core/algorithms.py", line 567, in factorize
    assume_unique=True)
  File "/usr/local/lib/python3.6/site-packages/pandas/core/algorithms.py", line 490, in safe_sort
    ordered = sort_mixed(values)
  File "/usr/local/lib/python3.6/site-packages/pandas/core/algorithms.py", line 476, in sort_mixed
    nums = np.sort(values[~str_pos])
  File "/usr/local/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 822, in sort
    a.sort(axis=axis, kind=kind, order=order)
TypeError: '<' not supported between instances of 'Period_t' and 'Period_t'
Uncaught exception. Entering post mortem debugging
Running 'cont' or 'step' will restart the program
> /usr/local/lib/python3.6/site-packages/numpy/core/fromnumeric.py(822)sort()
-> a.sort(axis=axis, kind=kind, order=order)
(Pdb)

**Comment by joyeez** [comment]
This is critical issue.  Needs to be addressed at highest level. FIX IT!

**Comment by joyeez** [comment]
Done by using total_order in BackTestTypes.py
