### ISSUE TITLE
issue status: 逻辑问题，non-blocking issue. 未解决，需要改进

### ISSUE THREAD

**Issue by joyeez** [joyeez/rc_backTest#4]
lib/OptionChecker.py 需要考虑options._user_id 为None的情形

    def test_id_with_user_id_chk(self):
        '''Check whether -test_id option goes together with -user_id'''
        if self.options._test_id is not None and self.options._user_id is not None:
            self.error("%s: Option (-t (or --test_id) and -u (or --user_id) ). Only one option can be taken. Modify the options and then rerun. Exit" %(SysErr_t.WOIS.value))
        specified_users = re.split('[ \t,;]+', self.options._user_id)
        if self.options._user_id is not None and len(specified_users) > 1:
            self.error("%s: Option (-u (or --user_id) ) by today can support ONLY ONE user but you specified %s users (%s). Exit" %(SysErr_t.WOIS.value, len(specified_users), specified_users))

**Comment by joyeez** [comment]
[songpj@localhost tests]$ python3 ../bin/rc_backTest.py
=======================================================
Racing Capital Security Back Test System (v0.1)
=======================================================
10-11-17 06:35 INFO: (rc_backTest.utils) Set working directory to /home/songpj/PycharmProjects/rc_backTest/tests
Traceback (most recent call last):
  File "../bin/rc_backTest.py", line 64, in <module>
    rc_backTest = rc_backTest()
  File "../bin/rc_backTest.py", line 51, in __init__
    self.OptChecker = OptionChecker(("%s.OptChecker" %(self._name)), self)
  File "/home/songpj/PycharmProjects/rc_backTest/bin/../lib/OptionChecker.py", line 31, in __init__
    self.test_id_with_user_id_chk()
  File "/home/songpj/PycharmProjects/rc_backTest/bin/../lib/OptionChecker.py", line 72, in test_id_with_user_id_chk
    specified_users = re.split('[ \t,;]+', self.options._user_id)
  File "/usr/local/lib/python3.6/re.py", line 212, in split
    return _compile(pattern, flags).split(string, maxsplit)
TypeError: expected string or bytes-like object

**Comment by joyeez** [comment]
ISS10112017_4 is solved
