### ISSUE TITLE
lib/Portfolio.py vs. position_track (from 'portfolio')

### ISSUE THREAD

**Issue by joyeez** [joyeez/rc_backTest#7]
解决方案, 将lib/Portfolio.py中的表名称改为position_track (from 'portfolio')
    def __init__(self, name, test_id, parent):
        super(Portfolio, self).__init__(name+"_"+str(test_id), parent, test_id, "position_track")

10-11-17 07:47 UDEBUG: (rc_backTest.DataFeeder.StrategyTemplate) Enter rc_backTest.DataFeeder.StrategyTemplate strategy
10-11-17 07:47 DEBUG: (rc_backTest.DataFeeder.Context_2341837) get unique values of column (sec_grp)
10-11-17 07:47 DEBUG: (rc_backTest.DataFeeder.Context_2341837) get security groups (['CN_STK'])
10-11-17 07:47 INFO: (rc_backTest.DataFeeder.StrategyTemplate.SecType_t.CNSTK_MKT) Open...
10-11-17 07:48 DEBUG: (rc_backTest.TableMgr) Add in one table and then I have (1) tables
Traceback (most recent call last):
  File "/usr/local/pycharm-community-2017.2.3/helpers/pydev/pydevd.py", line 1599, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/usr/local/pycharm-community-2017.2.3/helpers/pydev/pydevd.py", line 1026, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/usr/local/pycharm-community-2017.2.3/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/songpj/PycharmProjects/rc_backTest/bin/rc_backTest.py", line 66, in <module>
    rc_backTest.main()
  File "/home/songpj/PycharmProjects/rc_backTest/bin/rc_backTest.py", line 60, in main
    self.DataFeeder.main()
  File "/home/songpj/PycharmProjects/rc_backTest/bin/../lib/DataFeeder/DataFeeder.py", line 35, in main
    self.per_test_id_proc(test_id)
  File "/home/songpj/PycharmProjects/rc_backTest/bin/../lib/DataFeeder/DataFeeder.py", line 58, in per_test_id_proc
    with _strategy(("%s.%s" %(self._name, ts_strategy)), parent=self, context = context) as cur_strategy:
  File "/home/songpj/PycharmProjects/rc_backTest/bin/../lib/StrategyRunner/AnyStrategy.py", line 56, in __enter__
    self.build_facilities()
  File "/home/songpj/PycharmProjects/rc_backTest/bin/../lib/StrategyRunner/AnyStrategy.py", line 64, in build_facilities
    self.Portfolio = Portfolio(self._name, self.test_id, self)
  File "/home/songpj/PycharmProjects/rc_backTest/bin/../lib/Portfolio.py", line 23, in __init__
    super(Portfolio, self).__init__(name+"_"+str(test_id), parent, test_id, "portfolio")
  File "/home/songpj/PycharmProjects/rc_backTest/bin/../lib/TableMgr/AnyTable.py", line 35, in __init__
    self.tbl_columns = self.TableMgr.SqlDbCenter.get_table_column_names(table_name)
  File "/home/songpj/PycharmProjects/rc_backTest/bin/../lib/SqlDbCenter/SqlDbCenter.py", line 133, in get_table_column_names
    cols = self.all_dbs[db_name].get_table_column_names(table_name)

**Comment by joyeez** [comment]
I deliberately changed the table name from "position_track" to "portfolio" in the SQL table.  would it be better to call it portfolio than "position_track"?

**Comment by joyeez** [comment]
Corrected back to position_back because it makes more sense based on the concept of portfolio. Close this issue and done.
